In [11]:
import bs4
import requests
import pandas as pd


def profit_and_loss(url):
    res = requests.get(url)
    try:
        res.raise_for_status()
    except:
        return 'Webpage not valid'

    soup = bs4.BeautifulSoup(res.content, 'html.parser')
    # Arriving at table of profit and loss statement with classes and ids
    table_data = soup.find(class_ = 'tab-pane fade active in', id = 'standalone-new')
    if table_data == None:
        return 'Webpage not valid'
    table_body = table_data.find(class_ = 'mctable1')


    table_for_columns = table_data.find_all('tr')
    list_of_columns = []
    for i in table_for_columns:
        list_of_columns.append(i.find('td').text)
    list_of_columns = [i for i in list_of_columns if i != u'\xa0']

    # Each element of table_body_list = row of profit and loss statement
    table_body_list = table_body.find_all('td')
    list_of_elements = []
    for i in table_body_list:
        list_of_elements.append(i.text)
    list_of_elements = [i for i in list_of_elements if i != u'\xa0']

    dict_data = {}
    for i in list_of_columns:
        if i in list_of_elements:
            num = list_of_elements.index(i)
            dict_data[i] = list_of_elements[num + 1: num + 6]

    return dict_data


base_url = 'https://www.moneycontrol.com/financials/relianceindustries/consolidated-profit-lossVI/ri'
list_of_dict = []
count = 0
while True:
    if count == 0:
        url = base_url + '#ri'
    else:
        url = base_url + '/' + str(count + 1) + '#ri'
    dic = profit_and_loss(url)
    if dic == 'Webpage not valid':
        break
    list_of_dict.append(profit_and_loss(url))
    count = count + 1

df = pd.DataFrame.from_dict(list_of_dict[0])
df

,Profit & Loss account of Reliance Industries (in Rs. Cr.),INCOME,Revenue From Operations [Gross],Less: Excise/Sevice Tax/Other Levies,Revenue From Operations [Net],Total Operating Revenues,Other Income,Total Revenue,EXPENSES,Cost Of Materials Consumed,...,Profit/Loss For The Period,Minority Interest,Consolidated Profit/Loss After MI And Associates,OTHER ADDITIONAL INFORMATION,EARNINGS PER SHARE,Basic EPS (Rs.),Diluted EPS (Rs.),DIVIDEND AND DIVIDEND PERCENTAGE,Equity Share Dividend,Tax On Dividend
0,Mar 20,,"659,205.00","62,462.00","596,743.00","596,743.00","13,956.00","610,699.00",,"260,621.00",...,"39,773.00",-526.00,"39,354.00",,,63.00,63.00,,"3,852.00",732.00
1,Mar 19,,"625,212.00","56,003.00","569,209.00","569,209.00","8,386.00","577,595.00",,"275,237.00",...,"39,734.00",-249.00,"39,588.00",,,67.00,67.00,,"3,554.00",728.00
2,Mar 18,,"430,731.00","39,054.00","391,677.00","391,677.00","9,949.00","401,626.00",,"207,448.00",...,"36,021.00",-5.00,"36,075.00",,,61.00,61.00,,"3,255.00",661.00
3,Mar 17,,"330,180.00","24,798.00","305,382.00","305,382.00","9,443.00","314,825.00",,"175,087.00",...,"29,941.00",68.00,"29,901.00",,,101.00,101.00,,0.00,0.00
4,Mar 16,,"293,298.00","19,299.00","273,999.00","273,999.00","12,053.00","286,052.00",,"158,199.00",...,"29,625.00",-116.00,"29,745.00",,,101.00,101.00,,"6,039.00","1,220.00"

In [15]:
for i in list_of_dict[1:]:
    for k, v in i.items():
        df[k] = v
df

ValueError: Length of values does not match length of index